language: perl
sudo: false

addons:
  postgresql: "9.3"

perl:
  - '5.14'
  - '5.16'
  - '5.18'
  - '5.20'
  - 'blead'

env:
  global:
    - PG_PORT=5432

matrix:
  include:
    - perl: 5.18
      env:
        - COVERAGE=1
        - 'HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,local,^t/"'
  allow_failures:
    - perl: blead

branches:
  except:
    - releases

before_install:
  - git config --global user.name "TravisCI"
  - git config --global user.email $HOSTNAME":not-for-mail@travis-ci.org"
  - git fetch --unshallow || true
  - git fetch origin master:master
  - git fetch origin releases:releases
  - git clone --depth=1 git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - '[ `perlbrew lib list` ] || perlbrew lib create travis'
  - perlbrew use $PERLBREW_PERL@travis
  - perl -V
  - build-dist
  - cd $BUILD_DIR

install:
  - cpan-install Devel::Cover
  - cpan-install --deps
  - cpan-install --coverage

before_script:
  - coverage-setup

script:
  - prove -j$(test-jobs) $(test-files)   # parallel testing

after_success:
  - coverage-report

cache:
  directories:
    - $PERLBREW_HOME/libs

notifications:
  email:
    recipients:
      - sedlakmichal@gmail.com
    on_success: change
    on_failure: always
